import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "../_components/site-footer";
import { SiteHeader } from "../_components/site-header";
import { RoasCalculator } from "./roas-calculator";

export const metadata: Metadata = {
  title: "ROAS Calculator - Calculate Return on Ad Spend | ToolPiko",
  description:
    "Use ToolPiko's free ROAS calculator to calculate return on ad spend, campaign profit, profit margin, and revenue needed to reach your target ROAS.",
  alternates: {
    canonical: "/roas-calculator",
  },
};

const faqs = [
  {
    question: "How do you calculate ROAS?",
    answer:
      "To calculate ROAS, divide the revenue generated by an advertising campaign by the amount spent on ads. For example, $4,000 in revenue divided by $1,000 in ad spend equals a 4.00x ROAS.",
  },
  {
    question: "What does a 4x ROAS mean?",
    answer:
      "A 4x ROAS means your campaign generated $4 in revenue for every $1 spent on advertising.",
  },
  {
    question: "Is ROAS the same as profit?",
    answer:
      "No. ROAS compares revenue with ad spend, while profit also accounts for product costs, fees, fulfillment, and other business expenses.",
  },
  {
    question: "Can ROAS be below 1?",
    answer:
      "Yes. A ROAS below 1 means the campaign generated less revenue than the amount spent on advertising before other costs are considered.",
  },
  {
    question: "Should I include costs in ROAS?",
    answer:
      "The standard ROAS formula uses only revenue and ad spend. However, considering COGS and other expenses helps you determine whether a campaign is actually profitable.",
  },
  {
    question: "What is a good ROAS?",
    answer:
      "There is no single good ROAS for every business. Your profitable ROAS depends on gross margin, product costs, fees, fulfillment expenses, and your growth goals.",
  },
];

export default function RoasPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <main className="min-h-screen bg-white text-slate-950">
      <SiteHeader />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(faqSchema).replace(/</g, "\\u003c"),
        }}
      />

      <section className="mx-auto max-w-6xl px-5 py-12 sm:px-6 sm:py-16 lg:px-8">
        <div className="max-w-3xl">
          <p className="mb-4 text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">
            Free marketing calculator
          </p>

          <h1 className="text-4xl font-bold tracking-tight text-slate-950 sm:text-5xl">
            ROAS Calculator
          </h1>

          <p className="mt-5 text-lg leading-8 text-slate-600">
            Use this free ROAS calculator to calculate return on ad spend and
            see how much revenue your advertising generates for every dollar
            spent. You can also estimate campaign profit, profit margin, and the
            revenue required to reach your target ROAS.
          </p>

          <p className="mt-4 text-base leading-7 text-slate-600">
            Planning your advertising goals? Use the{" "}
            <Link
              href="/target-roas-calculator"
              className="font-semibold text-slate-950 underline decoration-teal-300 underline-offset-4 hover:decoration-teal-600"
            >
              Target ROAS Calculator
            </Link>{" "}
            to work out the ROAS your campaign needs to achieve.
          </p>
        </div>

        <div className="mt-10">
          <RoasCalculator />
        </div>
      </section>

      <section className="border-y border-slate-200 bg-slate-50">
        <div className="mx-auto grid max-w-6xl gap-8 px-5 py-16 sm:px-6 lg:grid-cols-[0.7fr_1fr] lg:px-8">
          <div>
            <p className="text-sm font-semibold uppercase tracking-[0.18em] text-teal-700">
              ROAS Guide
            </p>
            <h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">
              How to Calculate Return on Ad Spend
            </h2>
          </div>

          <div className="space-y-10">
            <ContentSection title="What Is ROAS?">
              <p>
                ROAS stands for return on ad spend. It measures how much revenue
                an advertising campaign generates compared with the amount
                spent on advertising.
              </p>
              <p className="mt-4">
                For example, if you spend $1,000 on ads and generate $4,000 in
                revenue, your ROAS is 4.00x. In other words, the campaign
                generated $4 in revenue for every $1 spent.
              </p>
            </ContentSection>

            <ContentSection title="ROAS Formula">
              <p className="mb-4">
                The standard return on ad spend formula is:
              </p>

              <div className="rounded-lg border border-slate-200 bg-white p-5 font-mono text-sm leading-7 text-slate-800">
                <p>ROAS = Revenue / Ad Spend</p>
              </div>

              <p className="mt-4">
                You can express ROAS as a multiple such as 4.00x or as a
                percentage. A 4.00x ROAS is equivalent to a 400% return on ad
                spend.
              </p>
            </ContentSection>

            <ContentSection title="How to Calculate ROAS">
              <p>
                To calculate ROAS, take the total revenue attributed to your
                advertising campaign and divide it by the total amount spent on
                ads.
              </p>

              <div className="mt-5 rounded-lg border border-slate-200 bg-white p-5">
                <p className="font-semibold text-slate-950">
                  Example ROAS calculation
                </p>
                <p className="mt-3">
                  Revenue: $4,000
                  <br />
                  Ad spend: $1,000
                  <br />
                  ROAS: $4,000 / $1,000 = 4.00x
                </p>
              </div>

              <p className="mt-4">
                This means the advertising campaign produced $4 of revenue for
                every $1 spent.
              </p>
            </ContentSection>

            <ContentSection title="How to Use the ROAS Calculator">
              <p>
                Enter your advertising spend and the revenue generated by the
                campaign. The calculator will automatically work out your ROAS.
                You can also enter product costs and other expenses to estimate
                campaign profitability.
              </p>

              <p className="mt-4">
                If you already know the ROAS you want to achieve, enter your
                target ROAS to calculate the revenue your campaign needs to
                generate.
              </p>
            </ContentSection>

            <ContentSection title="ROAS, Profit and Margin Calculations">
              <div className="rounded-lg border border-slate-200 bg-white p-5 font-mono text-sm leading-7 text-slate-800">
                <p>ROAS = Revenue / Ad Spend</p>
                <p>Profit After Ad Spend = Revenue - Ad Spend</p>
                <p>
                  Profit After All Costs = Revenue - Ad Spend - COGS - Other
                  Costs
                </p>
                <p>
                  Profit Margin % = Profit After All Costs / Revenue x 100
                </p>
                <p>Required Revenue = Ad Spend x Target ROAS</p>
              </div>
            </ContentSection>

            <ContentSection title="What Is a Good ROAS?">
              <p>
                A good ROAS depends on your gross margin, product costs,
                fulfillment expenses, fees, and growth goals. A campaign can
                have a high ROAS and still produce little profit if margins are
                low.
              </p>

              <p className="mt-4">
                Use the{" "}
                <Link
                  href="/profit-margin-calculator"
                  className="font-semibold text-slate-950 underline decoration-teal-300 underline-offset-4 hover:decoration-teal-600"
                >
                  Profit Margin Calculator
                </Link>{" "}
                to understand how much of your revenue remains after costs.
              </p>
            </ContentSection>

            <ContentSection title="ROAS vs ROI">
              <p>
                ROAS measures revenue generated from advertising compared with
                advertising spend. ROI measures profit compared with the total
                investment made.
              </p>

              <p className="mt-4">
                ROAS is especially useful for comparing advertising campaign
                efficiency, while ROI provides a broader view of overall
                profitability.
              </p>
            </ContentSection>

            <ContentSection title="ROAS vs CPA">
              <p>
                ROAS measures how much revenue is generated for every dollar of
                ad spend. CPA measures how much it costs to acquire one customer
                or conversion.
              </p>

              <p className="mt-4">
                Use the{" "}
                <Link
                  href="/cpa-calculator"
                  className="font-semibold text-slate-950 underline decoration-teal-300 underline-offset-4 hover:decoration-teal-600"
                >
                  CPA Calculator
                </Link>{" "}
                when you want to measure acquisition cost instead of revenue
                efficiency.
              </p>
            </ContentSection>

            <ContentSection title="Break-Even ROAS">
              <p>
                Break-even ROAS is the minimum return on ad spend required to
                cover your costs without making a loss. It depends heavily on
                your profit margin.
              </p>

              <p className="mt-4">
                Use the{" "}
                <Link
                  href="/break-even-roas-calculator"
                  className="font-semibold text-slate-950 underline decoration-teal-300 underline-offset-4 hover:decoration-teal-600"
                >
                  Break-Even ROAS Calculator
                </Link>{" "}
                to calculate the minimum ROAS your business needs.
              </p>
            </ContentSection>

            <ContentSection title="Target ROAS">
              <p>
                Target ROAS is the return on ad spend you want an advertising
                campaign to achieve. It can help you determine how much revenue
                you need from a given advertising budget.
              </p>

              <p className="mt-4">
                Calculate your advertising goal with the{" "}
                <Link
                  href="/target-roas-calculator"
                  className="font-semibold text-slate-950 underline decoration-teal-300 underline-offset-4 hover:decoration-teal-600"
                >
                  Target ROAS Calculator
                </Link>
                .
              </p>
            </ContentSection>

            <ContentSection title="How to Improve ROAS">
              <p>
                Improving ROAS usually means generating more revenue from the
                same advertising budget or reducing wasted ad spend. Common
                approaches include improving conversion rates, increasing
                average order value, testing better ad creative, improving
                audience targeting, and optimizing landing pages.
              </p>

              <p className="mt-4">
                Businesses should also monitor margins because a higher ROAS
                does not automatically guarantee higher profit.
              </p>
            </ContentSection>

            <ContentSection title="Frequently Asked Questions">
              <div className="space-y-4">
                {faqs.map((faq) => (
                  <details
                    key={faq.question}
                    className="rounded-lg border border-slate-200 bg-white p-5"
                  >
                    <summary className="cursor-pointer text-base font-semibold text-slate-950">
                      {faq.question}
                    </summary>
                    <p className="mt-3 text-sm leading-6 text-slate-600">
                      {faq.answer}
                    </p>
                  </details>
                ))}
              </div>
            </ContentSection>
          </div>
        </div>
      </section>

      <SiteFooter />
    </main>
  );
}

function ContentSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-2xl font-bold tracking-tight text-slate-950">
        {title}
      </h2>
      <div className="mt-4 text-base leading-8 text-slate-600">{children}</div>
    </section>
  );
}